on: push

jobs: 
  build-and-deply: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    # The flutter action needs java so include it
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Cache Flutter dependencies
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter
    # Include the flutter action
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'  
    # Get flutter packages
    - run: flutter pub get
    # Build the full apk
    #- run: flutter build apk
    - name: dummy
      run: mkdir -p "build/app/outputs/apk/release" && touch "build/app/outputs/apk/release/app-release.apk"
    #- name: Step 3 - Use the Upload Artifact GitHub Action
    #  uses: actions/upload-artifact@v2
    #  with: 
    #    name: all-for-download
    #    path: build
    - name: Step 4 - Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: app-download
        path: build/app/outputs/apk/release/app-release.apk
        
    - name: deploy apk
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: build/app/outputs/apk/release
        # repo: paetzold/newmobility
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: build/app/outputs/apk/release
        github_token: 2eb61a0292860e49c5a21ea96ef2916c98b6f55e
        branch: gh-pages
        repository: paetzold/newmobilty
